perception:
    right_camera:
        pointcloud_projection_node:
            ros__parameters:
                camera_info_topic: "/sensing/right_camera/camera_info"
                pointcloud_array_topic: "/perception/points_array"