costmap_filter_node:
  ros__parameters:
    grid_map_topic : "/perception/grid_map"
    filters:    
      filter1:  # Set lower threshold filter
        name: lower_threshold
        type: gridMapFilters/ThresholdFilter
        params:
          layer: combined
          lower_threshold: 0.3
          set_to: 0.0