front_lidar_pointcloud_to_laserscan_node:
    ros__parameters:
        target_frame: 'front_lidar'
        transform_tolerance: 0.01
        min_height : -3.0
        max_heitht : 3.0
        angle_min : -1.5708
        angle_max : 1.5708
        angle_increment: 0.0087
        scan_time : 0.3333
