front_velodyne_scan_segmentation_node:
    ros__parameters:
        scan_topic : "scan"
        max_segment_distance : 0.8
        min_segment_distance : 0.1
        distance_ratio : 2.0
        theta_threashold : 0.3141592653589793
        output_frame_id : "front_velodyne"
        visualize_frame_id : "map"