points_concatenate_node:
    ros__parameters:
        num_input: 4
        input_topic:
            0 : "/perception/front_lidar/radius_outlier_removal_node/output"
            1 : "/perception/rear_lidar/radius_outlier_removal_node/output"
            2 : "/perception/left_lidar/radius_outlier_removal_node/output"
            3 : "/perception/right_lidar/radius_outlier_removal_node/output"
